global:
  cloudprovider: "dev"

autosharding:
  enabled: false

replicas: 1

kubeStateMetrics:
  image:
    repository: kubesphere/kube-state-metrics
    tag: v2.10.1
    digest: sha256:af8220f534938de121a694cb7314313a6195c9d494fc30bfa6885b08a276bb82
    pullPolicy: IfNotPresent

fullnameOverride: kube-state-metrics
prometheusScrape: true

service:
  port: 8080
  # Default to clusterIP for backward compatibility
  type: ClusterIP
  nodePort: 0
  loadBalancerIP: ""
  clusterIP: ""
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
