name: Test RenovateBot

on:
  push:

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: read
  statuses: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: ./config.js
        env:
          LOG_LEVEL: debug
          RENOVATE_DOCKER_USER: ${{ secrets.RENOVATE_DOCKER_USER }}
          RENOVATE_DOCKER_PASS: ${{ secrets.RENOVATE_DOCKER_PASS }}
